index:
  # 首页 Banner 头图，可以是相对路径或绝对路径，以下相同
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  # 头图高度，屏幕百分比
  banner_img_height: 100

post:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 80

  
archive:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 80

  
category:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 80

tag:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 80
  
about:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 40
  
links:
  banner_img: https://101.43.39.125/HexoFiles/new/bg-trans.png
  banner_img_height: 60
  items:
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "/img/favicon.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "/img/favicon.png"
    }
